name: Camel actions

on:
	pull_request: master
	
env:
	CARGO_TERM_COLOR: always

jobs:
	- format:
		- runs_on: ubuntu-latest
		
		- uses: actions/checkout@v3
		- run: |
			cargo fmt --check
			sudo apt-get install shfmt; shfmt -i 4 -d .
	
	- lint:
		- needs: format
		- runs_on: ubuntu-latest
		
		- uses: actions/checkout@v3
		- uses: ludeeus/action-shellcheck@2.0.0
		- run: |
			cargo clippy --verbose -- -D warnings
	
	- test:
		- needs: lint
		- runs_on: ubuntu-latest
		
		- uses: actions/checkout@v3
		- uses: taiki-e/install-action@cargo-llvm-cov
		- uses: codecov/codecov-action@v3
		- run: |
			cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
	
