name: ci

on:
	pull_request: master
	
env:
	CARGO_TERM_COLOR: always
	FORMAT: true

jobs:
	format:
		env:
			FORMAT_SHELL: true
		
		if: {{env.FORMAT == true}}
		runs_on: ubuntu-latest
		
		steps:
			- uses: actions/checkout@v3
			- run: cargo fmt --check
			- run: sudo apt-get install shfmt; shfmt -i 4 -d .
			  if: {{env.FORMAT_SHELL == true}}
	
	lint:
		env:
			CARGO_TERM_COLOR: always
		
		needs: [format]
		runs_on: ubuntu-latest
		
		steps:
			- uses: actions/checkout@v3
			- uses: ludeeus/action-shellcheck@2.0.0
			- run: cargo clippy --verbose -- -D warnings
	
	test:
		
		needs: [lint]
		runs_on: ubuntu-latest
		
		steps:
			- uses: actions/checkout@v3
			  with:
				submodules: true
			- uses: taiki-e/install-action@cargo-llvm-cov
			- uses: codecov/codecov-action@v3
			  with:
				files: codecov.json
				fail_ci_if_error: true
			- run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
	
